server:
  port: 8080
  servlet:
    context-path: /Serendipity
spring:
  application:
    name: Serendipity
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.209.223:3306/Serendipity?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: wyj
    password: "05156420"
  thymeleaf:
    cache: false
  redis:
    host: 47.101.209.223
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
    password: 642005
  devtools:
    restart:
      enabled: true
      additional-paths: src/main
      exclude: static/jar/**
mybatis:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
